Add some style
FatecSorocaba/callforpapersXXIV pull request #7
Opened 2017-07-31 23:48 UTC by medson10

2017-08-01 12:29 UTC, CaiqueMitsuoka commented
Some style ???

2017-08-01 14:15 UTC, CaiqueMitsuoka requested changes

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/fonts.scss
> +
There is no point in leave an empty line inside a block, unless it is used for some reason, like separate different things.

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/fonts.scss
> +    option {
Here could have a new line to separate the class from the attributes :nail_care:

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/fonts.scss
> +
useless new line :nail_care:

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/fonts.scss
> +  h3 {
new line please :nail_care:

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/variables.scss
> +  &:focus {
new line :nail_care:

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/variables.scss
> +
useless new line

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +    <h2>Palestrante</h2>
Its better to leave the `h2` outside the form, since it is not a content of the form.

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +      <%= form.label :foto %>
Here the label is referring to `:picture`, so it should be `<%= form.label :picture %>`, if you want to change the output text of the field you should pass it as a the second arg like `<%= form.label :picture , 'foto' %>`.
You can read more here: http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormHelper.html#method-i-label

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +      <%= form.file_field :picture, class: :inputpicture %>
Its better to pass the class as a string. `<%= form.file_field :picture, class: 'inputpicture' %>`

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +      <%= form.label :empresa %>
same here

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +      <%= form.label :biografia %>
same here

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +      <%= form.text_field :company, class: :input%>
class as string

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +      <%= form.text_area :biography, class: :textarea %>
class as string

2017-08-01 14:15 UTC, CaiqueMitsuoka commented on app/views/speakers/_form.html.erb
> +        <%= talk_form.label :titulo %>
im going to stop say 'same here', but you get the idea. It is valid for all the form fields.

2017-08-01 17:08 UTC, felipesoares6 requested changes

2017-08-01 17:08 UTC, felipesoares6 commented on app/assets/stylesheets/base/variables.scss
> +    background:$inputActive;
you can add a whitespace between the key and the value here, after the `:`

2017-08-01 17:08 UTC, felipesoares6 commented on app/views/layouts/application.html.erb
> +        Para saber mais entre no <a href="#"><i>site oficial do evento</i></a>
here you can change the `#` to the real website https://fatecsorocaba.github.io/semana-da-tecnologia/

2017-08-01 17:08 UTC, felipesoares6 commented on app/views/layouts/application.html.erb
> +     <a href="#"><h3>SETEC - Site Oficial</h3></a>
the same thing here put the real link :)

2017-08-10 16:20 UTC, CaiqueMitsuoka approved these changes

2017-08-10 16:22 UTC, felipesoares6 approved these changes

2017-08-10 16:22 UTC, merged