Feat/add responsive layout
FatecSorocaba/callforpapersXXIV pull request #8
Opened 2017-08-18 05:12 UTC by medson10

2017-08-18 14:29 UTC, felipesoares6 requested changes

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
>  .buttonsubmit {
What do you think about putting a name like this: `button-submit`, in my opinion, this way is better to increase the legibility, I saw that you put all the class names like this, can you change the others too?

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
> +    h1, h2, h3 {
when you put a selector like this, to increase the legibility is better like 
 ```
h1,
h2,
h3
```

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
> +        font-size: 55px;
remove the extra space here 💅

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
> +    background-image: image-url("");
what is that? if you haven't the src I think you can remove this line

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
>      #signup {
Why did you use an id here? If is just a normal style it's better to keep using a class instead of id.

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
>      }
break one line here before this selector 💅

2017-08-18 14:29 UTC, felipesoares6 commented on app/assets/stylesheets/base/fonts.scss
>      #titleTalk {
The same thing about using ids, it's better just keep with classes

2017-08-18 14:33 UTC, medson10 commented on app/assets/stylesheets/base/fonts.scss
> +    background-image: image-url("");
that is to remove the background image from header

2017-08-18 14:33 UTC, medson10 commented on app/assets/stylesheets/base/fonts.scss
>  .buttonsubmit {
ok, i'll

2017-08-18 14:50 UTC, felipesoares6 commented
I saw that all these styles are inside of the same file, doesn't seem right and the name `fonts` when I read this sound like a file that just defines the font-family of the project.

2017-08-19 05:40 UTC, medson10 commented
Ok, i understand, Caique has spoken already about that. I removed the code from the font file and left only the code that defines the fonts. I created new files and divided the code between them, take a look when you have a time.

2017-08-22 00:21 UTC, felipesoares6 commented on app/assets/stylesheets/base/form.scss
> +  box-shadow: 0.5px 0.5px 0.5px 0.5px #888888;
if all values are `0.5px` you can use just one or less than that? and what about change this `#888888`  to `#888`

2017-08-22 00:21 UTC, felipesoares6 commented on app/assets/stylesheets/base/form.scss
> +  box-shadow: 0.5px 0.5px 0.5px 0.5px #888888;
when you use the `0.5`, you can add just the `.5`

2017-08-22 00:21 UTC, felipesoares6 commented on app/assets/stylesheets/base/general.scss
> +  text-decoration: none !important;
why you need this `!important` here?

2017-08-22 06:33 UTC, medson10 commented on app/assets/stylesheets/base/form.scss
> +  box-shadow: 0.5px 0.5px 0.5px 0.5px #888888;
in box-shadow the value cannot be setted in this way

2017-08-23 14:07 UTC, felipesoares6 approved these changes

2017-08-23 14:08 UTC, felipesoares6 commented
boa Medson 👏   🎉

2017-08-23 14:08 UTC, CaiqueMitsuoka commented
:clap:

2017-08-23 14:08 UTC, merged