Ft/style error messages
FatecSorocaba/callforpapersXXIV pull request #9
Opened 2017-09-01 04:18 UTC by medson10

2017-09-01 19:19 UTC, felipesoares6 approved these changes

2017-09-01 21:14 UTC, CaiqueMitsuoka requested changes

2017-09-01 21:14 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/form.scss
> +  list-style-type:decimal;
WHY?

2017-09-01 21:17 UTC, CaiqueMitsuoka commented on app/assets/stylesheets/base/form.scss
> +  list-style-type:decimal;
If you are using an `ul` tag, which is a unordered list, why list them in a decimal way? is make sense if it is an ordered list. Either way, in this case, make no sense be an ordered list.

2017-09-01 21:20 UTC, felipesoares6 requested changes

2017-09-01 21:20 UTC, felipesoares6 commented on app/views/speakers/_form.html.erb
> +      <h2 class="error-title"><%= pluralize(speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>
I think we can remove this `:` at the final of the sentence

2017-09-02 17:11 UTC, CaiqueMitsuoka approved these changes

2017-09-02 17:13 UTC, felipesoares6 approved these changes

2017-09-02 17:13 UTC, merged